---
title: "Chapter_2_Analysis"
output: html_document
date: "2023-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
list.files(.libPaths()[1])  %>%
  purrr::walk(~library(.x, character.only = TRUE))

setBaseDirectory("~/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome")
good.shapes = c(1:25,33:127)
meta_16s <- downloadSequenceMetadata(startYrMo = "2014-07", endYrMo = "2022-07",
                                     sites = c("GRSM"),
                                     targetGene = "16S")

meta_16s_qc <- qcMetadata(meta_16s, pairedReads = "Y")

meta <- qcMetadata(meta_16s, pairedReads = "Y", rmFlagged = "Y")
meta$date_ymd <- as.Date(format(as.Date(meta$collectDate, format="%Y-%m-%d %H:%M:%S"), "%Y-%m-%d"))

soils <- downloadSoilData(startYrMo = "2014-07", endYrMo = "2022-07",sites = c("GRSM"))

select_columns <- c("domainID", "siteID", "plotID", "plotType", "nlcdClass", "collectDate", 
                    "sampleTiming", "standingWaterDepth", "sampleID", 
                    "horizon", "soilTemp", "litterDepth", "sampleTopDepth", "sampleBottomDepth", 
                    "geneticSampleID", "soilInCaClpH")
soils <- soils[, select_columns]

sampledata <- merge(meta, soils, all.x=T, by = "geneticSampleID")

remove <- which(duplicated(sampledata$geneticSampleID) == T)
#163

sampledata <- sampledata[-remove,]

# Add rownames to sample data table 
rownames(sampledata) <- sampledata$dnaSampleID
```

```{r clean data}
ps <- readRDS(file.path(NEONMICROBE_DIR_OUTPUTS(), "NEON_16S_phyloseq_grsm.Rds"))
ps <- taxa_prune(ps, "Archaea", classification="Kingdom", na.rm=TRUE)
ps <- tax_fix(ps) # try tax_fix_interactive if you have problems with your own data
ps <- phyloseq_validate(ps, remove_undetected = TRUE)

keep <- c("plotID.x", "date_ymd", "nlcdClass", "dnaSampleID",
          "sampleTiming", "sampleID", "horizon", "soilTemp", "soilInCaClpH")
keep.sites <- c("GRSM_002", "GRSM_001","GRSM_007", "GRSM_016", "GRSM_055", "GRSM_058", "GRSM_059", "GRSM_060", "GRSM_003")

ps <- subset_samples(ps, ps@sam_data$plotID.x %in% keep.sites)

ps@sam_data <- ps@sam_data[,keep]

for(i in 1:nrow(ps@sam_data)){
  if(ps@sam_data$plotID.x[i] == "GRSM_001"){
    ps@sam_data$fire[i] <- "Unburned"
  }
  if(ps@sam_data$plotID.x[i] == "GRSM_002"){
    ps@sam_data$fire[i] <- "Unburned"
  }
  if(ps@sam_data$plotID.x[i] == "GRSM_003"){
    ps@sam_data$fire[i] <- "Burned"
  }
  if(ps@sam_data$plotID.x[i] == "GRSM_007"){
    ps@sam_data$fire[i] <- "Burned"
  }
  if(ps@sam_data$plotID.x[i] == "GRSM_016"){
    ps@sam_data$fire[i] <- "Unburned"
  }
  if(ps@sam_data$plotID.x[i] == "GRSM_055"){
    ps@sam_data$fire[i] <- "Burned"
  }
  if(ps@sam_data$plotID.x[i] == "GRSM_058"){
    ps@sam_data$fire[i] <- "Burned"
  }
  if(ps@sam_data$plotID.x[i] == "GRSM_059"){
    ps@sam_data$fire[i] <- "Burned"
  }
  if(ps@sam_data$plotID.x[i]== "GRSM_060"){
    ps@sam_data$fire[i] <- "Burned"
  }
}

ps@sam_data$year <- stringr::str_extract(ps@sam_data$date_ymd, "^.{4}")

for(i in 1:nrow(ps@sam_data)){
  if(ps@sam_data$year[i] == "2016"){
    ps@sam_data$Time[i] <- "Pre-"
  }
  if(ps@sam_data$year[i] == "2017"){
    ps@sam_data$Time[i] <- "Post-"
  }
}

#Convert to VST for non alpha-diversity measures
ps.vst <- vst_transform(ps)
ps.vst@otu_table[ps.vst@otu_table < 0.0] <- 0.0
```

```{r alpha diversity analysis}
ps_rare <- rarefy_even_depth(ps, sample.size=10000, rngseed=101010) #Value from Rocca Paper
alpha_div <- cbind("dnaSampleID" = get_variable(ps_rare, "dnaSampleID"), estimate_richness(ps_rare, measures = c("Observed", "Shannon")))
alpha_div <- merge(sampledata, alpha_div, by="dnaSampleID", all.y=TRUE)
alpha_div$fire <- NA

#Add in Fire Data
for(i in 1:nrow(alpha_div)){
  if(alpha_div$plotID.x[i] == "GRSM_001"){
    alpha_div$fire[i] <- "Unburned"
  }
  if(alpha_div$plotID.x[i] == "GRSM_002"){
    alpha_div$fire[i] <- "Unburned"
  }
  if(alpha_div$plotID.x[i] == "GRSM_003"){
    alpha_div$fire[i] <- "Burned"
  }
  if(alpha_div$plotID.x[i] == "GRSM_007"){
    alpha_div$fire[i] <- "Burned"
  }
  if(alpha_div$plotID.x[i] == "GRSM_016"){
    alpha_div$fire[i] <- "Unburned"
  }
  if(alpha_div$plotID.x[i] == "GRSM_055"){
    alpha_div$fire[i] <- "Burned"
  }
  if(alpha_div$plotID.x[i] == "GRSM_058"){
    alpha_div$fire[i] <- "Burned"
  }
  if(alpha_div$plotID.x[i] == "GRSM_059"){
    alpha_div$fire[i] <- "Burned"
  }
  if(alpha_div$plotID.x[i]== "GRSM_060"){
    alpha_div$fire[i] <- "Burned"
  }
}

alpha_div$year <- stringr::str_extract(alpha_div$date_ymd, "^.{4}")
alpha_div$yearmonth <- stringr::str_extract(alpha_div$date_ymd, "^.{7}")

alpha_div$Time <- NA
for(i in 1:nrow(alpha_div)){
  if(alpha_div$year[i] == "2016"){
    alpha_div$Time[i] <- "Pre-"
  }
  if(alpha_div$year[i] == "2017"){
    alpha_div$Time[i] <- "Post-"
  }
}

alpha_div$fire <- factor(alpha_div$fire, levels = c("Unburned", "Burned"))
alpha_div$Time <- factor(alpha_div$Time, levels = c("Pre-", "Post-"))

Fig2a <- ggplot(alpha_div, aes(x=fire, y=Observed, fill = Time)) +
              geom_boxplot(na.rm = T) +
              ylab("Observed ASV Richness") +
              xlab("Fire Status") +
  scale_fill_manual(values = c("#002244","#FB4F14")) +
  theme_cowplot(12) +
  labs(color = expression("Time")) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12), 
        legend.position="none") +
  stat_compare_means(mapping = NULL, comparisons = NULL, hide.ns = TRUE,
                     label = "p.signif",  label.x = NULL, label.y = NULL)

Fig2b <- ggplot(alpha_div, aes(x=fire, y=Shannon, fill = Time)) +
  geom_boxplot(na.rm = T) +
  ylab("Observed Shannon Diversity") +
  xlab("Fire Status") +
  scale_fill_manual(values = c("#002244","#FB4F14")) +
  theme_cowplot(12) +
  labs(color = expression("Time")) +
  ylim(5, 7)  +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12), 
        legend.position="none") +
  stat_compare_means(mapping = NULL, comparisons = NULL, hide.ns = TRUE,
                     label = "p.signif",  label.x = NULL, label.y = NULL)

legend <- get_legend(
  Fig2a + guides(color = guide_legend(nrow = 1)) + theme(legend.position = "bottom", legend.title = element_text(size = 12), legend.text = element_text(size = 12))) #+ 
  #scale_fill_viridis(labels = c(expression(paste0("5: ", ""))
#)

#Statistical Tests
alpha.burned <- alpha_div[alpha_div$fire == "Burned",]
alpha.unburned <- alpha_div[alpha_div$fire == "Unburned",]

pre <- alpha.burned[alpha.burned$Time == "Pre-",c("Observed", "Shannon")]
post <- alpha.burned[alpha.burned$Time == "Post-",c("Observed", "Shannon")]
burned.obs <- wilcox.test(x = pre$Observed, y = post$Observed,
            alternative = c("two.sided"),
            mu = 0, paired = TRUE, exact = FALSE, correct = TRUE,
            conf.int = FALSE, conf.level = 0.95)

burned.shannon <- wilcox.test(x = pre$Shannon, y = post$Shannon,
            alternative = c("two.sided"),
            mu = 0, paired = TRUE, exact = NULL, correct = TRUE,
            conf.int = FALSE, conf.level = 0.95)

pre <- alpha.unburned[alpha.unburned$Time == "Pre-",c("Observed", "Shannon")]
post <- alpha.unburned[alpha.unburned$Time == "Post-",c("Observed", "Shannon")]

unburned.obs <- wilcox.test(x = pre$Observed, y = post$Observed,
            alternative = c("two.sided"),
            mu = 0, paired = FALSE, exact = NULL, correct = TRUE,
            conf.int = FALSE, conf.level = 0.95)

unburned.shannon <- wilcox.test(x = pre$Shannon, y = post$Shannon,
            alternative = c("two.sided"),
            mu = 0, paired = FALSE, exact = NULL, correct = TRUE,
            conf.int = FALSE, conf.level = 0.95)

un <- alpha.unburned[alpha.unburned$Time == "Pre-",c("Observed", "Shannon")]
b <- alpha.burned[alpha.burned$Time == "Pre-",c("Observed", "Shannon")]

pre.test.obs <- wilcox.test(x = un$Observed, y = b$Observed,
            alternative = c("two.sided"),
            mu = 0, paired = FALSE, exact = FALSE, correct = TRUE,
            conf.int = FALSE, conf.level = 0.95)

pre.test.shannon <- wilcox.test(x = un$Shannon, y = b$Shannon,
            alternative = c("two.sided"),
            mu = 0, paired = FALSE, exact = FALSE, correct = TRUE,
            conf.int = FALSE, conf.level = 0.95)

#ANOVA
alpha.burned <- alpha_div[alpha_div$fire == "Burned",]

#Check for Normality
levene_test(Observed ~ Time,
  data = alpha.burned)

div.aov <- anova_test(Observed ~ soilTemp + soilInCaClpH + Time + sampleTiming,
  data = alpha.burned)

shan.aov <- anova_test(Shannon ~ soilTemp + soilInCaClpH + Time + sampleTiming,
  data = alpha.burned)

# Make this into a GGPLOT Figure for the Supplemental Materials
par(mfrow = c(1, 2)) # combine plots

# histogram
hist(div.aov$residuals)

# QQ-plot
library(car)
qqPlot(div.aov$residuals,
  id = FALSE # id = FALSE to remove point identification
)

#KW
physeq <- ps.burned
physeq <- taxa_level(physeq,"Genus")
physeq@sam_data$Time <- as.factor(physeq@sam_data$Time)
kw_sig <-  kruskal_abundance(physeq, "Time")
#plot the significant features
plot_signif(kw_sig$plotdata)


a <- ggplot(alpha.burned, aes(x=plotID.x, y=Observed, fill = Time)) +
              geom_boxplot(na.rm = T) +
              ylab("Observed ASV Richness") +
              xlab("Plot ID") +
  scale_fill_manual(values = c("#002244","#FB4F14")) +
  theme_cowplot(12) +
  labs(color = expression("Time")) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12), 
        legend.position="none") +
  stat_compare_means(mapping = NULL, comparisons = NULL, hide.ns = TRUE,
                     label = "p.signif",  label.x = NULL, label.y = NULL)

b <- ggplot(alpha.burned, aes(x=plotID.x, y=Shannon, fill = Time)) +
  geom_boxplot(na.rm = T) +
  ylab("Observed Shannon Diversity") +
  xlab("Plot ID") +
  scale_fill_manual(values = c("#002244","#FB4F14")) +
  theme_cowplot(12) +
  labs(color = expression("Time")) +
  ylim(4, 8)  +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12), 
        legend.position="none") +
  stat_compare_means(mapping = NULL, comparisons = NULL, hide.ns = TRUE,
                     label = "p.signif",  label.x = NULL, label.y = NULL)

legend <- get_legend(
  a + guides(color = guide_legend(nrow = 1)) + theme(legend.position = "bottom", legend.title = element_text(size = 12), legend.text = element_text(size = 12)) #+ 
  #scale_fill_viridis(labels = c(expression(paste0("5: ", ""))
)

Figure_Tmp <- plot_grid(a,b, labels = c("A", "B"))
Figure2 <- plot_grid(Figure_Tmp, legend, ncol = 1, rel_heights  = c(1, .1), align = "v", axis = "lr") 


ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/Supplemental_Figure1.pdf", 
       plot = Figure2, width = 180, height = 90, units=c("mm"), dpi=600) 

```

```{r heatmap}
heatplot <- ps.vst %>% 
  tax_transform(trans = "rclr", rank = "Phylum") %>% 
  tax_filter(min_prevalence = 0.1, use_counts = TRUE) %>% 
  comp_heatmap(
    colors = heat_palette(sym = TRUE), grid_col = NA, 
    sample_side = "bottom", name = "Robust\nCLR",
    sample_anno = sampleAnnotation(
      "Sample" = anno_sample("status"), 
      col = list("Sample" = c(
        "Pre-Unburned" = "#7851A9", "Post-Unburned" = "#9272BB", "Pre-Burned" = "#A97851", "Post-Burned" = "#BB9272"
      ))
    )
  )

supplemental_heatplot <- ps.vst %>% 
  tax_transform(trans = "rclr", rank = "Genus") %>% 
  tax_filter(min_prevalence = 0.1, use_counts = TRUE) %>% 
  comp_heatmap(
    colors = heat_palette(sym = TRUE), grid_col = NA, 
    sample_side = "bottom", name = "Robust\nCLR",
    sample_anno = sampleAnnotation(
      "Sample" = anno_sample("status"), 
      col = list("Sample" = c(
        "Pre-Unburned" = "#7851A9", "Post-Unburned" = "#9272BB", "Pre-Burned" = "#A97851", "Post-Burned" = "#BB9272"
      ))
    )
  )
```

```{r PERMANOVA}
# Subset to only the Burned plots
ps.burned <- subset_samples(ps, fire = "Burned")

ps_perm <- ps.burned %>% 
  tax_transform("identity", rank = "Genus") %>% 
  dist_calc("bray") %>% 
  dist_permanova(
    variables = c("sampleTiming", "soilTemp", "soilInCaClpH", 
                  "Time"),
    n_perms = 10000, # you should use more permutations in your real analyses!
    n_processes = 1)

ps_perm %>% perm_get()
print(ps_perm)
```

```{r correlation plots}
p <- ggcorrmat(
  data = alpha_div,
      cor.vars = c(sampleTiming, standingWaterDepth, soilInCaClpH, fire, year),
    cor.vars.names = c(
    "Sample Timing",
    "Water Depth",
    "Soil pH",
    "Fire Status",
    "Year"
  ),
  colors   = c("#002244","white","#FB4F14"),
  type         = "parametric", ## correlation method,
  ggcorrplot.args = list(
    tl.srt = 45,
    pch.col = "white",
    outline.color = "white", hc.order = TRUE,
    pch.cex = 4
  )
) + 
  theme(legend.position="right")

FigureS1 <- plot_grid(FigureSTEMP, legend, nrow = 1, rel_widths = c(1, .05), align = "h", axis = "tb")

ggsave(filename= paste0(manuscript, "/Figures/FigureS1.pdf"), 
       plot = FigureSTEMP, width = 180, height = 300, units=c("mm"), dpi=600) 
```

```{r Figure 3}
ps.burned@sam_data$Time <- factor(ps.burned@sam_data$Time, levels = c("Pre-", "Post-"))

#RDA Plot of Significant Predictors
ps.weighted <- ps.burned %>%
  ps_mutate(
    pH = c(scale(soilInCaClpH, center = TRUE, scale = TRUE)),
    Fire = if_else(fire == "Burned" & Time == "Post-", 1, 0),
    Spring = if_else(sampleTiming == "winterSpringTransition" & Time == "Post-", 1, 0),
    Summer = if_else(sampleTiming == "peakGreenness" & Time == "Post-", 1, 0),
    Fall = if_else(sampleTiming == "fallWinterTransition" & Time == "Post-", 1, 0),
    GRSM_001 = if_else(plotID.x == "GRSM_001", 1, 0),
    GRSM_002 = if_else(plotID.x == "GRSM_002", 1, 0),
    GRSM_003 = if_else(plotID.x == "GRSM_003", 1, 0),
    GRSM_007 = if_else(plotID.x == "GRSM_007", 1, 0),
    GRSM_016 = if_else(plotID.x == "GRSM_016", 1, 0),
    GRSM_055 = if_else(plotID.x == "GRSM_055", 1, 0),
    GRSM_058 = if_else(plotID.x == "GRSM_058", 1, 0),
    GRSM_059 = if_else(plotID.x == "GRSM_059", 1, 0),
    GRSM_060 = if_else(plotID.x == "GRSM_060", 1, 0))

constr.ord <- ps.weighted %>%
  tax_filter(min_prevalence = 0.1, tax_level = "Genus") %>%
  tax_agg("Genus") %>%
  tax_transform("hellinger") %>%
  ord_calc(method = "RDA", conditions = c("GRSM_001", "GRSM_003", "GRSM_007",
                                          "GRSM_055", "GRSM_058", "GRSM_059",
                                          "GRSM_060"), 
           constraints = c("pH", "Fire", "Spring", "Summer", "Fall")) %>% 
  ord_plot(color = "Time", shape = "plotID.x", size = 2, alpha = 1, show.legend = FALSE) +
  scale_colour_manual(values = c("#002244","#FB4F14", "")) +
  scale_shape_manual(values=good.shapes)

constr.ord <- constr.ord +
  theme(axis.text=element_text(size=8),
        axis.title=element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8)) +
  theme_cowplot(12) +
  labs(color='Time', shape = "Plot") + 
  ggside::geom_xsidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) +
  ggside::geom_ysidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) +
  ggside::theme_ggside_void()

ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/Figure3A.pdf", 
       plot = constr.ord, width = 180, height = 180, units=c("mm"), dpi=600)

#MDS Plot of Bray Curtis
ps.bray <-  ps.burned %>%
  dist_calc(dist = "bray") %>%
  ord_calc(method = "PCoA") %>% 
  ord_plot(color = "Time", shape = "plotID.x", size = 2, alpha = 1,
           show.legend = FALSE) +
  scale_colour_manual(values = c("#002244","#FB4F14", "")) +
  scale_shape_manual(values=good.shapes)

bd <-  ps.burned %>%
  dist_calc(dist = "bray") %>%
  dist_bdisp(variables = c("sampleTiming", "soilTemp", "soilInCaClpH", "Time")) %>%
  bdisp_get()

ps.bray <- ps.bray +
  theme(axis.text=element_text(size=8),
        axis.title=element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8)) +
  theme_cowplot(12) +
  labs(color='Fire Status', shape = "Plot") + 
  ggside::geom_xsidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) +
  ggside::geom_ysidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) +
  ggside::theme_ggside_void()

ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/Figure3B.pdf", 
       plot = ps.bray, width = 180, height = 180, units=c("mm"), dpi=600)

#Root Tree
#ps.rooted <- root_phyloseq_tree(ps.burned)

#Unifrac Distance plot for Beta-Diversity
#unifrac <- ps.rooted %>%
#  tax_transform("identity", rank = "unique") %>% 
#  dist_calc("gunifrac", gunifrac_alpha = 0.5)

#unifrac.plot <- unifrac %>% 
#  ord_calc(method = "PCoA") %>%
#  ord_plot(color = "Time", shape = "plotID.x", size = 2, alpha = 1, #show.legend=FALSE) +
#  scale_colour_manual(values = c("#002244","#FB4F14", "")) +
#  scale_shape_manual(values=good.shapes)

#unifrac.plot <- unifrac.plot +
#  theme(axis.text=element_text(size=8),
#        axis.title=element_blank(),
#        axis.text.x = element_blank(),
#        axis.ticks = element_blank(),
#        legend.text=element_text(size=8)) +
#  theme_cowplot(12) +
#  labs(color='Fire Status', shape = "Site") + 
#  ggside::geom_xsidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) #+
#  ggside::geom_ysidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) #+
#  ggside::theme_ggside_void() 


#PCA and Iris Plot of Shannon
 ps.pca <-  ps.burned %>%
 tax_filter(min_prevalence = 2.5 / 100, verbose = FALSE) %>%
  tax_transform(rank = "Genus", trans = "clr", zero_replace = "halfmin") %>%
  ord_calc(method = "PCA") %>%
  ord_plot(color = "Time", shape = "plotID.x", size = 2, alpha = 1) +
  scale_colour_manual(values = c("#002244", "#FB4F14", "")) +
  scale_shape_manual(values=good.shapes)

ps.pca <- ps.pca +
  theme(axis.text=element_text(size=8),
        axis.title=element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8)) +
  theme_cowplot(12) +
  labs(color='Fire Status', shape = "Site") + 
  ggside::geom_xsidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) +
  ggside::geom_ysidedensity(aes(fill = Time), alpha = 0.5, show.legend = FALSE) +
  ggside::theme_ggside_void() 

#ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/FigurePCA.pdf", 
#       plot = ps.pca, width = 180, height = 180, units=c("mm"), dpi=600)

#iris <- ps %>%
#  tax_filter(min_prevalence = 2.5 / 100, verbose = FALSE) %>%
#  tax_transform("clr", rank = "Phylum") %>% 
#  ord_calc(method = "PCA") %>%   
#  ps_mutate(Burned = Time == "Post-") %>%
#  ord_plot_iris(
#    tax_level = "Phylum", n_taxa = 31, other = "Other",
#    anno_colour = "fire", 
#    anno_colour_style = list(alpha = 0.6, size = 1, show.legend = FALSE)) +
#    theme(axis.text=element_text(size=8),
#        axis.title=element_blank(),
#        axis.text.x = element_blank(),
#        axis.ticks = element_blank(),
#        legend.text=element_text(size=8)) +
#  scale_colour_manual(values = c("#FB4F14", "#002244", "")) +
#  guides(fill=guide_legend(ncol=4))

## Old Figure 3C Idea
new.ps <- ps %>%
  tax_glom(taxrank = "Genus")%>%
  #transform_sample_counts(function(x){x/sum(x)})%>%
  psmelt()%>%
  arrange(Genus)

mycolors<-as.vector(brewer.paired(32))

new.ps$fire <- factor(new.ps$fire, levels = c("Unburned", "Burned"))
new.ps$Time <- factor(new.ps$Time, levels = c("Pre-", "Post-"))

Figure3C <- ggplot(new.ps,aes(x=Time, y=Abundance, fill=Phylum))+
  geom_bar(stat = "identity", position = "stack") + 
  facet_nested(.~fire+plotID.x,scales="free") +
  theme_cowplot(12) +
  scale_fill_manual(values=(mycolors), name="Phylum")+
  xlab("Samples") + ylab("Relative Abundance") +
  theme(axis.text=element_text(size=8),
        axis.title=element_blank(),
        axis.text.x =element_text(size=8),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8),
        legend.position = "bottom", 
        strip.background = element_rect(fill="white", colour = NA),
        strip.text = element_text(color="black",size=8, face="bold")) +
  guides(fill=guide_legend(keywidth = 0.5,keyheight = 0.5, ncol = 6))

legend <- get_legend(ps.pca + guides(color = guide_legend(nrow = 1)) + 
                       theme(legend.position = "bottom", legend.title = element_text(size = 8), legend.text = element_text(size = 8)))
Figure.Tmp <- plot_grid(ps.bray, constr.ord, nrow = 1, align = "v", axis = "tb", labels = c("A", "B"))
Figure.Tmp.2 <- plot_grid(Figure.Tmp, legend, ncol= 1, align = "h", rel_heights  = c(1,.1), axis = "lr")
legend.2 <- get_legend(Figure3CL + guides(color = guide_legend(ncol = 6)) + 
                       theme(legend.position = "bottom", legend.title = element_text(size = 8), legend.text = element_text(size = 8)))
Figure.Tmp.3 <- plot_grid(Figure3CL, legend.2, ncol= 1, align = "h", rel_heights  = c(1,.1), axis = "lr")
Figure3 <- plot_grid(Figure.Tmp.2, Figure3C, ncol = 1, align = "v", axis = "tb", labels = c("", "C")) 

ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/Figure3.pdf", 
       plot = Figure3, width = 180, height = 240, units=c("mm"), dpi=600)
```

```{r Supplementary Figure Tree}
#Set Level of Plotting
lm_models <- ps %>% 
  tax_fix() %>% 
  tax_prepend_ranks() %>% 
  tax_transform("compositional", rank = "Class", keep_counts = TRUE) %>% 
  tax_filter(min_prevalence = 0.1, undetected = 0, use_counts = TRUE) %>% 
  tax_transform(
    trans = "log2", chain = TRUE, zero_replace = "halfmin"
  ) %>% 
  taxatree_models(
    type = "lm", 
    ranks = c("Kingdom", "Phylum", "Class"), # uses every rank available except the first
    variables = c("nlcdClass", "soilInCaClpH", "fire", "Time")
  )

lm_stats <- taxatree_models2stats(lm_models)
lm_stats %>% taxatree_stats_get()

lm_stats <- taxatree_stats_p_adjust(
  data = lm_stats, method = "BH", grouping = "rank"
)

#Generate Key
set.seed(118) # label position 
key <- taxatree_plotkey(
  data = lm_stats, 
  taxon_renamer = function(x) stringr::str_remove(x, "[PC]: "),
  # 2 lines of conditions below, for filtering taxa to be labelled
  rank == "Phylum" | rank == "Class" & prevalence > 0.25, 
  !grepl("Kingdom", taxon)
) + 
  # add a bit more space for the longer labels by expanding the x axis
  scale_x_continuous(expand = expansion(mult = 0.2))
# all phyla are labelled, and all genera with a prevalence of over 0.2
# except for any taxa whose names (partly) match "Kingdom" 
# (i.e. an unclassified taxon)
key

lm_stats %>% taxatree_plots(
  node_size_range = c(1, 3)) %>% 
  patchwork::wrap_plots(
    ncol = 2, guides = "collect"
  )

#### Beta Bionmial Regression and Tree
bb_models <- ps.fire %>% 
  tax_fix() %>% 
  tax_prepend_ranks() %>% 
  tax_filter(min_prevalence = 0.3) %>% 
  taxatree_models(
    type = corncob::bbdml, 
    ranks = c("Phylum", "Class", "Order", "Family", "Genus"),
    variables = c("soilInCaClpH", "Time")
  )

bb_models

bb_stats <- taxatree_models2stats(bb_models, param = "mu")
bb_stats %>% taxatree_stats_get()

alt_trees <- bb_stats %>% 
  taxatree_plots(
    node_size_range = c(1, 4), circular = FALSE, colour_trans = "identity"
  ) %>% 
  # keep only first 4 plots
  .[1:2] %>% 
  patchwork::wrap_plots(
    ncol = 2, guides = "collect"
  ) & # & is used by patchwork to modify multiple ggplots (instead of +)
  coord_flip() & 
  scale_y_reverse()

alt_tree_key <- bb_stats %>% 
  taxatree_plotkey(circular = FALSE, .draw_label = FALSE, rank == "Family"
  ) %>% 
  taxatree_plot_labels(
    circular = FALSE, hjust = 0.5, force = 0, nudge_y = 2, size = 3,
    taxon_renamer = function(x) stringr::str_remove(x, "[PFG]: ")
  )  + 
  coord_flip() + 
  scale_y_reverse(expand = expansion(add = c(0.5, 1.5))) +
  theme(plot.title = element_text(size = 14))

patchwork::wrap_plots(alt_tree_key, alt_trees, nrow = 2, heights = 1:2)
```

```{r indic species analysis}
#If the site classification vector is obtained independently of species data, the significance of statistical tests carried out on the indicator species will be meaningful. For example, one could classify the sites using environmental data before indicator species analysis. An example is found in Borcard et al. 2011
# Phylum Level Indic Species Analysis
ps.phylum <- tax_glom(ps, taxrank = "Genus")
#ps.phylum <- ps

ps.matrix <- veganotu(ps.phylum) 
ps.env <- vegansam(ps.phylum)

ps.ven <- ps.env[,c("fire")]
ps.pre <- which(ps.env[,"Time"] == "Pre-")
ps.post <- which(ps.env[,"Time"] == "Post-")
ps.matrix.pre <- ps.matrix[ps.pre,]
ps.ven.pre <- ps.ven[ps.pre]

ps.ven.full <- ps.env[,c("fire", "Time")]
reduced <- which(ps.ven.full[,"fire"] == "Burned")
ps.ven.reduced <- ps.ven.full[reduced,]
ps.matrix.reduced <- ps.matrix[reduced,]
ps.ven.reduced <- as.data.frame(ps.ven.reduced)
ps.ven.reduced$Time <- as.factor(ps.ven.reduced$Time)

ps.ven.reduced <- ps.ven.reduced[,-1]

ps.matrix.post <- ps.matrix[ps.post,]
ps.ven.post <- ps.ven[ps.post]

ps.ven.pre <- as.data.frame(ps.ven.pre)
ps.ven.pre$fire <- as.factor(ps.ven.pre$ps.ven.pre)

ps.ven.post <- as.data.frame(ps.ven.post)
ps.ven.post$fire <- as.factor(ps.ven.post$ps.ven.post)
ps.ven.post <- ps.ven.post[,"fire"]

#Indic Species Analysis for Genus Level
indval <- multipatt(ps.matrix.reduced, ps.ven.reduced, fun = "r.g", control = how(nperm=811))

summary(indval)
```

```{r genus responses}
#Response to Fire
positive.response <- c('ASV589',
                       'ASV1920',
                       'ASV382',
                       'ASV2222',
                       'ASV405',
                       'ASV86',
                       'ASV5508',
                       'ASV2332',
                       'ASV2461',
                       'ASV1439',
                       'ASV2775',
                       'ASV2021',
                       'ASV2064',
                       'ASV2108',
                       'ASV120',
                       'ASV673',
                       'ASV2331',
                       'ASV3555',
                       'ASV5312',
                       'ASV3257',
                       'ASV1060',
                       'ASV1224',
                       'ASV975',
                       'ASV731',
                       'ASV4056',
                       'ASV749',
                       'ASV903',
                       'ASV341',
                       'ASV330',
                       'ASV1577',
                       'ASV1182',
                       'ASV508',
                       'ASV514',
                       'ASV736',
                       'ASV694',
                       'ASV860',
                       'ASV3755',
                       'ASV1400',
                       'ASV1941',
                       'ASV953')

negative.response <- c('ASV721',
                       'ASV632',
                       'ASV155',
                       'ASV4542',
                       'ASV3023',
                       'ASV490',
                       'ASV25',
                       'ASV15',  
                       'ASV181',  
                       'ASV242',  
                       'ASV365', 
                       'ASV1398', 
                       'ASV1276', 
                       'ASV1017', 
                       'ASV536',  
                       'ASV19',   
                       'ASV1442', 
                       'ASV531',
                       'ASV199', 
                       'ASV83',   
                       'ASV5',   
                       'ASV388',  
                       'ASV112',  
                       'ASV804', 
                       'ASV1828', 
                       'ASV498',  
                       'ASV298',  
                       'ASV511',  
                       'ASV3489', 
                       'ASV340', 
                       'ASV4282',
                       'ASV1232',
                       'ASV153', 
                       'ASV1884', 
                       'ASV2232', 
                       'ASV99',   
                       'ASV4524', 
                       'ASV569',  
                       'ASV1889', 
                       'ASV594', 
                       'ASV3730',
                       'ASV4094',
                       'ASV429',  
                       'ASV1306', 
                       'ASV4548', 
                       'ASV5388', 
                       'ASV185', 
                       'ASV2235',
                       'ASV495',
                       'ASV362',
                       'ASV1057', 
                       'ASV1326',
                       'ASV57',  
                       'ASV425',  
                       'ASV547', 
                       'ASV968',
                       'ASV72',   
                       'ASV1509',
                       'ASV12',
                       'ASV2625',
                       'ASV1037',
                       'ASV769',
                       'ASV191',
                       'ASV39',
                       'ASV132',
                       'ASV3434',
                       'ASV2608',
                       'ASV907')

positive.response <- as.data.frame(positive.response)
negative.response <- as.data.frame(negative.response)

negative.response$response <- "Burn (-)"
positive.response$response <- "Burn (+)"

colnames(negative.response)[1] <- "ASV"
colnames(positive.response)[1] <- "ASV"


responses <- rbind(positive.response, negative.response)
#filter.rows <-which(rownames(ps@tax_table) %in% responses == TRUE)

#otu.trim <- ps@otu_table[,filter.rows]
#tax.trim <- ps@tax_table[filter.rows]
#sam.trim <- ps@sam_data[filter.rows]
#phy.trim <- ps@phy_tree[filter.rows,]
#ref.trim <- ps@refseq[filter.rows]

#ps.trim <- phyloseq(otu_table(otu.trim, taxa_are_rows=FALSE),
#               sample_data(sam.trim),
#               tax_table(tax.trim),
#               phy_tree(ps@phy_tree))

#tree <- phy_tree(ps.trim)

ps.genus <- ps %>%
  tax_glom(taxrank = "Genus")

tree.data <- tax_table(ps.genus)
rownames(responses) <- responses$ASV

tree.data <- merge(tree.data, responses, by = 0, all.x=TRUE)
colnames(tree.data)[1] <- "ASV"
tree.data <- tree.data[,-8]
print(colnames(tree.data))
rownames(tree.data) <- tree.data$ASV 

for(i in 1:nrow(tree.data)){
  if(is.na(tree.data$response[i] == TRUE)){
    tree.data$response[i] <- "Burn (0)"
  }
  else{}
}
# Now, I have a data frame with the additional annotation information. Want to sort in the same way as dendogram before creating plot

```

```{r TITAN}
env <- ps.env[,c("soilInCaClpH", "fire")]
taxa <- ps.matrix

drop <- which(is.na(env))
print(drop)
52

env <- env[-52,]
taxa <- taxa[,-52]

titan.model <- titan(env, taxa,
minSplt = 5, numPerm = 250, boot = TRUE, nBoot = 500, imax = FALSE,
ivTot = FALSE, pur.cut = 0.75, rel.cut = 0.75, ncpus = 6, memory = FALSE
)
```

```{r Figure 4}
#############
tr <- ps.phylum@phy_tree
tree.data$SuperPhylum <- "NA"

for(i in 1:nrow(tree.data)){
  if(tree.data$Phylum[i] %in% c("Proteobacteria", "Myxococcota", "Acidobacteriota", "Bdellovibrionota", "RCP2-54", "Desulfobacterota", "Methylomirabilota", "NB1-j", 
                                "SAR324 clade(Marine group B)", "Dependentiae",
                                "Nitrospirota", "Entotheonellaeota", "MBNT15")){
    tree.data$SuperPhylum[i] <- "PANNAM"
  }
  if(tree.data$Phylum[i] %in% c("Actinobacteriota", "Firmicutes", "Armatimonadota", 
                                "WPS-2")){
    tree.data$SuperPhylum[i] <- "Terrabacteria"
  }
  if(tree.data$Phylum[i] %in% c("Planctomycetota", "Verrucomicrobiota")){
    tree.data$SuperPhylum[i] <- "PVC"
  }
  if(tree.data$Phylum[i] %in% c("Bacteroidota", "Latescibacterota", "FCPU426",
                                "Gemmatimonadota", "Fibrobacterota")){
    tree.data$SuperPhylum[i] <- "FCB"
  }
  if(tree.data$Phylum[i] %in% c("Patescibacteria", "GAL15", "Bacteria Kingdom", "FCPU426")){
    tree.data$SuperPhylum[i] <- "Bacteria Candidate Group"
  }
  if(tree.data$Phylum[i] %in% c("Chloroflexi")){
    tree.data$SuperPhylum[i] <- "CCD"
  }
  if(tree.data$Phylum[i] %in% c("Cyanobacteria")){
    tree.data$SuperPhylum[i] <- "CMS"
  }
  if(tree.data$Phylum[i] %in% c("Elusimicrobiota", "Spirochaetota")){
    tree.data$SuperPhylum[i] <- "Gracilicutes"
  }
  if(tree.data$Phylum[i] %in% c("Deinococcota")){
    tree.data$SuperPhylum[i] <- "DST"
  }
}

ps.phylum <- tax_names2rank(ps.phylum, colname = "SuperPhylum")

for(i in 1:nrow(ps.phylum@tax_table@.Data)){
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Proteobacteria", "Myxococcota", "Acidobacteriota", "Bdellovibrionota", "RCP2-54", "Desulfobacterota", "Methylomirabilota", "NB1-j", 
                                "SAR324 clade(Marine group B)", "Dependentiae",
                                "Nitrospirota", "Entotheonellaeota", "MBNT15")){
    ps.phylum@tax_table@.Data[i,7] <- "PANNAM"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Actinobacteriota", "Firmicutes", "Armatimonadota", 
                                "WPS-2")){
    ps.phylum@tax_table@.Data[i,7] <- "Terrabacteria"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Planctomycetota", "Verrucomicrobiota")){
    ps.phylum@tax_table@.Data[i,7] <- "PVC"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Bacteroidota", "Latescibacterota", "FCPU426",
                                "Gemmatimonadota", "Fibrobacterota")){
    ps.phylum@tax_table@.Data[i,7] <- "FCB"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Patescibacteria", "GAL15", "Bacteria Kingdom", "FCPU426")){
    ps.phylum@tax_table@.Data[i,7] <- "Bacteria Candidate Group"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Chloroflexi")){
    ps.phylum@tax_table@.Data[i,7] <- "CCD"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Cyanobacteria")){
    ps.phylum@tax_table@.Data[i,7] <- "CMS"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Elusimicrobiota", "Spirochaetota")){
    ps.phylum@tax_table@.Data[i,7] <- "Gracilicutes"
  }
  if(ps.phylum@tax_table@.Data[i,2] %in% c("Deinococcota")){
    ps.phylum@tax_table@.Data[i,7] <- "DST"
  }
}

tr.phylum = data.frame(id=tr$tip.label, val = rep(1, 550), group = tree.data$SuperPhylum)
tr.response = data.frame(id=tr$tip.label, val = rep(1, 550), group = tree.data$response)

otu.table <- as.matrix(otu_table(ps.genus))
abundance.table <- otu.table@.Data
sum.abund <- colSums(abundance.table)
tr.abundance = data.frame(id=tr$tip.label, val = sum.abund, group = tree.data$Phylum)



p <- ggtree(tr, branch.length='none', layout="circular", open.angle=10) 

p1 <- p + new_scale_fill() + 
           geom_fruit(
           data=tr.phylum, 
           geom=geom_tile,
           mapping=aes(y=id, fill=group),
           size=1) +
  scale_fill_manual(values=(mycolors), name="Phylum") + 
  theme(axis.text=element_blank(),
        axis.title=element_blank(),
        axis.text.x =element_blank(),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8),
        legend.position = "none")  +
  scale_fill_manual(values=mycolors)

p2 <- p1 + new_scale_fill() + geom_fruit(
           data=tr.response, 
           geom=geom_tile,
           mapping=aes(y=id, fill=group),
           size=1) +
  scale_fill_manual(values=c("#a97851", "#7851A9", "white")) +
  theme(axis.text=element_blank(),
        axis.title=element_blank(),
        axis.text.x =element_blank(),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8),
        legend.position = "none")

p3 <- p2 + new_scale_fill() + geom_fruit(
           data=tr.abundance, 
           geom=geom_boxplot,
           mapping=aes(y=id, fill=group),
           size=1) +
  theme(axis.text=element_blank(),
        axis.title=element_blank(),
        axis.text.x =element_blank(),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8),
        legend.position = "none")

legend <- get_legend(p1 + guides(color = guide_legend(ncol = 6)) + 
                       theme(legend.position = "bottom", legend.title = element_text(size = 8), legend.text = element_text(size = 8)))
legend.2 <- get_legend(p2 + guides(color = guide_legend(nrow = 1)) + 
                       theme(legend.position = "bottom", legend.title = element_text(size = 8), legend.text = element_text(size = 8)))
Legends.Tmp <- plot_grid(legend, legend.2, ncol = 1, align = "h", axis = "lr")
Figure.Tmp <- plot_grid(p2, legend.2, ncol= 1, align = "h", rel_heights  = c(1,.1), axis = "lr")

ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/Figure4.pdf", 
       plot = Figure.Tmp, width = 180, height = 240, units=c("mm"), dpi=600)

#Pagel's Lambda

# Add in data for Other Figure 4

df <- as.data.frame(tr.response[,3])
rownames(df) <- tr$tip.label
p <- ggtree(ps.phylum, branch.length='none', layout="circular", open.angle=10) +
     geom_tippoint(aes(color=SuperPhylum), shape = 15, show.legend = TRUE, size = 1)
  
p1 <- gheatmap(p, df, offset=.8, width=.2,
               colnames_angle=95, colnames_offset_y = .25)  +
  scale_fill_manual(values=c("#a97851", "#7851A9", "white")) +
  theme(axis.text=element_blank(),
        axis.title=element_blank(),
        axis.text.x =element_blank(),
        axis.ticks = element_blank(),
        legend.text=element_text(size=8),
        legend.position = "none")

legend <- get_legend(p + guides(color = guide_legend(ncol = 6)) + 
                       theme(legend.position = "bottom", legend.title = element_text(size = 8), legend.text = element_text(size = 8)))

legend.2 <- get_legend(p1 + guides(color = guide_legend(nrow = 1)) + 
                       theme(legend.position = "bottom", legend.title = element_text(size = 8), legend.text = element_text(size = 8)))
Legends.Tmp <- plot_grid(legend, legend.2, ncol = 1, align = "h", axis = "lr")
Figure.Tmp <- plot_grid(p1, legend.2, ncol= 1, align = "h", rel_heights  = c(1,.1), axis = "lr")

ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/Figure4.pdf", 
       plot = Figure.Tmp, width = 180, height = 240, units=c("mm"), dpi=600) 

```

```{r New Figure 2}
alpha_burned <- subset(alpha_div, alpha_div$fire == "Burned")
alpha_burned <- subset(alpha_burned, alpha_burned$Time == "Post-")
alpha_burned$sampleTiming <- factor(alpha_burned$sampleTiming, levels = c("winterSpringTransition", "peakGreenness",  "fallWinterTransition"))

#Sort into pre and post, combine all pre into one observation. Leave post as seperate observations
for(i in 1:nrow(alpha_div)){
  if(alpha_div$year[i] == 2016){
    alpha_div$timepoint[i] <- "2016"  
  }
  if(alpha_div$year[i] == 2017){
    if(alpha_div$sampleTiming[i] == "winterSpringTransition"){
      alpha_div$timepoint[i] <- "+3 Mon."
  }
    if(alpha_div$sampleTiming[i] == "peakGreenness"){
      alpha_div$timepoint[i] <- "+6 Mon."
  }
    if(alpha_div$sampleTiming[i] == "fallWinterTransition"){
      alpha_div$timepoint[i] <- "+9 Mon."
    }
  }
}

alpha_div$timepoint <- factor(alpha_div$timepoint, levels = c("2016", 
                                                              "+3 Mon.",
                                                              "+6 Mon.",
                                                              "+9 Mon."))

q <- ggplot(alpha_div, aes(x=timepoint, y=Observed, fill=timepoint)) +
              geom_boxplot(na.rm = T) +
              #geom_line(aes(color = plotID.x)) + 
              ylab("Observed ASV Richness") +
              xlab("Sample Timing") + 
  theme_cowplot(12) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12), 
        legend.position="none") +
  scale_fill_manual(values = c("#002244","#FB4F14", "#FB4F14", "#FB4F14"))

q1 <- ggplot(alpha_div, aes(x=timepoint, y=Shannon, fill=timepoint)) +
              geom_boxplot(na.rm = T) +
              #geom_line(aes(color = plotID.x)) + 
              ylab("Observed Shannon Diversity") +
              xlab("Sample Timing") + 
  theme_cowplot(12) +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12), 
        legend.position="none") +
  scale_fill_manual(values = c("#002244","#FB4F14", "#FB4F14", "#FB4F14"))

Figure_Tmp <- plot_grid(Fig2a,Fig2b,q, q1, labels = c("A", "B", "C", "D"), nrow = 2)
Figure2 <- plot_grid(Figure_Tmp, legend, ncol = 1, rel_heights  = c(1, .1), align = "v", axis = "lr") 


ggsave(filename= "/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/Documents/Duke/GRSM_Biome/Manuscript/Figure2.pdf", 
       plot = Figure2, width = 180, height = 180, units=c("mm"), dpi=600) 
```

```{r phyloD analysis}
response <- merge(tr.phylum, tr.response, by = "id")

response <- response[,c("group.x", "group.y")]

colnames(response) <- c("Clade", "Indicator")

chi.table <- table(summary.response$Clade, summary.response$Indicator)
chi.table <- chi.table[,-3]

chi.test <- chisq.test(chi.table)
```

```{r change by genus, before and after}
ps.phylum <- ps %>%
  tax_glom(taxrank = "Phylum")

otu.table <- as.matrix(otu_table(ps.phylum))
abundance.table <- otu.table@.Data

merged.table <- cbind(abundance.table, ps.env[,c("fire", "year")])
merged.data <- aggregate(.~fire+year, merged.table, sum)

colnames(merged.data) <- c("fire", "year", "Proteobacteria","Acidobacteriota","Actinobacteriota",
           "Verrucomicrobiota","RCP2-54","Planctomycetota", "WPS-2",
           "Bacteroidota","Chloroflexi","Myxococcota","Cyanobacteria",
           "Methylomirabilota","Gemmatimonadota","Dependentiae",
           "Patescibacteria","Firmicutes","Armatimonadota","Nitrospirota",
           "Entotheonellaeota","MBNT15","Elusimicrobiota","Desulfobacterota",
           "NB1-j","Bdellovibrionota","Latescibacterota","Bacteria Kingdom",
           "FCPU426","Fibrobacterota","SAR324 clade(Marine group B)",
           "Deinococcota","Spirochaetota","GAL15")

burned.data <- merged.data[merged.data$fire == "Burned",]
unburned.data <- merged.data[merged.data$fire == "Unburned",]

rownames(burned.data) <- c("Pre-", "Post-")
burned.data <- burned.data[,-1]
burned.data <- burned.data[,-1]
burned.data["Change",] <- ((burned.data["Post-",] - burned.data["Pre-",])/burned.data["Pre-",])*100

burned.data <- round(burned.data)

rownames(unburned.data) <- c("Pre-", "Post-")
unburned.data <- unburned.data[,-1]
unburned.data <- unburned.data[,-1]
unburned.data["Change",] <- ((unburned.data["Post-",] - unburned.data["Pre-",])/unburned.data["Pre-",])*100

unburned.data <- round(unburned.data)
```

```{r export table}
burned.data <- t(burned.data)

total.data <- colSums(burned.data)
total.data[3] <- ((total.data[2] - total.data[1])/total.data[1])*100

xtable(burned.data, type = "latex", file = "burnedchange.tex")
```